### ISSUE TITLE
Job Title

### ISSUE THREAD

**Issue by richardtaylordawson** [cadekynaston/gatsby-portfolio#2]
![Screen Shot 2019-09-21 at 3 39 30 PM](https://user-images.githubusercontent.com/25511178/65379490-15253880-dc86-11e9-91d4-e79c94b9678a.png)

I would change "software" to uppercase since it is a title :)

But better yet, I would change your title to "HTML Developer" since that is what you are.

**Comment by cadekynaston** [comment]
Thank you Richard!!!
